version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      
  www:
      image: nginx
      restart: always
      expose:
        - "80"
      volumes:
        - ${PATH1}:/usr/share/nginx/html:ro
      environment:
        - VIRTUAL_HOST=${HOSTNAMES} #EXAMPLE: web1.com,www.web1.com
        - LETSENCRYPT_HOST=${HOSTNAMES} #EXAMPLE: web1.com,www.web1.com
        - LETSENCRYPT_EMAIL=${EMAIL} # YOUR EMAIL
  www2:
      image: nginx
      restart: always
      expose:
        - "80"
      volumes:
        - ${PATH2}:/usr/share/nginx/html:ro
      environment:
        - VIRTUAL_HOST=${HOSTNAMES2} #EXAMPLE: web2.com,www.web2.com
        - LETSENCRYPT_HOST=${HOSTNAMES2} #EXAMPLE: web2.com,www.web2.com
        - LETSENCRYPT_EMAIL=${EMAIL} # YOUR EMAIL
volumes: 
  certs:
  html:
  vhostd:
